### PR TITLE
Move translation code into Renderer::Views::Base

### PR DESCRIPTION
**Pull request by dazoakley**
This will allow translations to be used the JSON views also.

### CODE REVIEW

**Comment by ettomatic** [comment]
Looks good to me! But Travis disagree :(

**Comment by samfrench** [comment]
This is a good idea. This is something a few of us were discussing recently.

**Comment by samfrench** [comment]
One thing that would be nice, is with our translations, to have a catch all:
```yaml
base:
  translation: value

specific_component:
  translation: value
```

Currently, we are specifying the same translations for many components, because it does a lookup based on the component name. This isn't for this PR, but something that would be good to address sometime.

**Comment by dazoakley** [comment]
@samfrench add it as an issue maybe?

**Comment by kodikos** [comment]
👍 once you've worked out the travis problems

**Pull request merged**
